version: "3"
services:
    db:
        image: postgres:10.7
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
        restart: always
    web:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
